" Don't try to be vi compatible
set nocompatible

" Turn on syntax highlighting
syntax on

colorscheme  badwolf
" Make the gutters darker than the background.
"let g:badwolf_darkgutter = 1
"colorscheme  molokai
"colorscheme  morning
"colorscheme  default
"colorscheme  monokai
"colorscheme  monokai2
"colorscheme  sublimemonokai
set t_Co=256
"set background=dark

" Show line numbers
set number
set guifont=Ubuntu\ Mono\ 14
"set guifont=Monospace\ 9
"set guifont=Monospace\ 10
"set guifont=Courier\ 10\ Pitch\ 12

" Whitespace
set tabstop=3
set shiftwidth=3
set softtabstop=3
set expandtab
set noshiftround

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

let loaded_matchparen = 1

" highlight column border at 80
"highlight ColorColumn ctermbg=darkgray
"set colorcolumn=80

" Airline settings
execute pathogen#infect()
filetype plugin indent on

" Airline settings
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'
" Airline theme settings
let g:airline_theme='badwolf'
"let g:airline_powerline_fonts = 1
" Disable all white space warnings in the end of airline
let g:airline#extensions#whitespace#enabled = 0

" CtrlSF configurations
let g:ctrlsf_auto_close = {
    \ "normal" : 0,
    \ "compact": 0
    \}

" ack & ag settings
nnoremap <F4> :CtrlSF<CR>
let g:ctrlsf_auto_focus = {
    \ "at": "done",
    \ "duration_less_than": 1000
    \ }
let g:ctrlsf_context = '-C 1'
let g:ctrlsf_position = 'right'

" buffer switch shortcut
nnoremap <silent>   <tab> :if &modifiable && !&readonly && &modified <CR> :write<CR> :endif<CR>:bnext<CR>
nnoremap <silent> <s-tab> :if &modifiable && !&readonly && &modified <CR> :write<CR> :endif<CR>:bprevious<CR>

" Display trailing spaces
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Enables cursor line position tracking:
set cursorline
" Removes the underline causes by enabling cursorline:
highlight clear CursorLine
" Sets the line numbering to red background:
" highlight CursorLineNR ctermbg=red

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
